services:
  mysql:
    image: mysql:8.4
    container_name: bank-products-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bank_products_registry_db
      MYSQL_USER: bank_user
      MYSQL_PASSWORD: bank_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot_password"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
